# Generated by Django 5.1.3 on 2025-03-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('family_name', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=32)),
                ('email_address', models.EmailField(error_messages={'required': 'メールアドレスは必須です。', 'unique': 'このメールアドレスはすでに使用されています'}, max_length=254, unique=True)),
                ('password', models.CharField(error_messages={'required': 'パスワードは必須です。'}, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='money', serialize=False, to='money_management.user')),
                ('amount', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('convenience_store', 'コンビニ'), ('food', '飲食店'), ('supermarket', 'スーパー'), ('cafe', 'カフェ'), ('other', 'その他')], default='convenience_store', max_length=17)),
                ('recorded_money', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='money_management.user')),
            ],
        ),
    ]
