# Generated by Django 5.1.3 on 2025-03-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
