# Generated by Django 5.1.3 on 2025-03-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_management', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
